cinder-databunny-driver:
  volume-backend-name : databunnystorage
  ixsystems_server_hostname : 10.0.50.250
  ixsystems_server_port : "80"
  ixsystems_server_iscsi_port : "3260"
  ixsystems_api_version : "2.0"
  ixsystems_volume_backend_name : databunnystorage
  ixsystems_vendor_name : iXsystem
  ixsystems_storage_protocol : iscsi
  ixsystems_transport_type : http
  ixsystems_login : root
  ixsystems_password : ""
  ixsystems_datastore_pool : osfast2
  ixsystems_dataset_path : osfast2/cinder
  ixsystems_reserved_percentage : "0"
  ixsystems_iqn_prefix : iqn.storage.databunny.sg
  ixsystems_portal_id : "1"
  ixsystems_initiator_id : "1"
  iscsi_helper : tgtadm
  volume_dd_blocksize : 1M
  volume_driver : driver.iscsi.FreeNASISCSIDriver